### ISSUE TITLE
Payment Start without checking the errors

### ISSUE THREAD

**Issue by raatool** [paylike/plugin-easy-digital-downloads#10]
Hello, I installed this payment plugin. On the checkout page, when I press the Place Order button the payment will start without checking the fields errors. Can you help me, please?

Thanks!

**Comment by ionutcalara** [comment]
Hi @raatool the EDD plugin hasn't been updated in a long time. The main reason is that the plugin developers didn't really provide a proper documentation for their updates, and it wasn't an option to keep up. However, I will have a look at your version and see if we can make modifications, but it will take some time. 

Can you please send me a screenshot of your checkout page and the EDD version you are using along with the WooCommerce version?

**Comment by ionutcalara** [comment]
I am closing this but feel free to reopen when you have more information.
