### ISSUE TITLE
PlugIn

### ISSUE THREAD

**Issue by 1212-mother** [paylike/plugin-easy-digital-downloads#9]
Hi
we use normal Wordpress page, tried to use Easy Digital Downloads - Paylike Payment Gateway plugIn. We followed the guideline from Paylike. After downloading and activating to click into the Settings this message is coming: "Sorry, you do not have access to connect with this page".
Please help us to solve this problem.
Thanks a lot,
MotherNature Association
Hungary

Jo napot,
nem tudom, hogy magyarul is tudják-e olvasni. Egyszerű wordpress oldalon szeretnénk használni az Easy Digital Downloads - Paylike Payment Gateway plugint. A honlapjukon leírtak szerint telepítettük.  Letöltés és aktiválás után a Beállításokra kattintva a következő üzenet jelenik meg: "Elnézést, nincs megfelelő jogosultság ehhez az oldalhoz kapcsolódni. 
Kérem segítsenek megoldani ezt a problémát.
köszönettel

**Comment by ionutcalara** [comment]
Hi @1212-mother can you please let me know what version of easy digital downloads you tested with, and what role was the user you tried with?

**Comment by 1212-mother** [comment]
1.5.1.  version of Easy digital downloads and my role is Administrator role.

**Comment by ionutcalara** [comment]
1.5.1 is the version of our plugin, but you also need the main EDD plugin here: https://easydigitaldownloads.com/ . Did you install that one?

**Comment by 1212-mother** [comment]
Now we downloaded and seems working! Thanks a lot! It was not clear for us that this main EDD is needed. 
Can we costum the payment form here?

**Comment by ionutcalara** [comment]
Hi @1212-mother, some experience with EDD would be helpful, as far as paylike goes, you will need the approval to use the embedded card fields. Those are customizable to some extent. Please contact support and make sure your account is allowed to use the credit card fields. 
I will close this issue, but if you further questions, feel free to reopen. 

Thank you,
Ionut

**Comment by 1212-mother** [comment]
Thanks a lot!

Liza 
MotherNature
